url = https://qa01.mps-aws.com/
url_admin= https://qa01.mps-aws.com/mps_admin
username = akshay.chauhan@monolithicpower.com
userpassword = Iforgot@123
useradminname = akshay.chauhan@monolithicpower.com
useradminpassword = Thisisqapassword1
browserName = chrome
Base_url= https://qa01.mps-aws.com/
testrail.url=https://mpswebqanew.testrail.io/
testrail.username=mpswebqanew@gmail.com
testrail.apiKey=TjFQ.JXS9G010t4F0rx7-p7Ro5mvUOk8zzoAHi2oM
testrail.projectId=2
testrail.suiteId=1
testrail.runId=1
